import path from "node:path";
import { inflateRawSync } from "node:zlib";
import type {
  WorkspaceOfficePreview,
  WorkspaceOfficePreviewBlock,
  WorkspaceOfficePreviewKind,
  WorkspacePreviewKind,
} from "@/app/types/workspace";

const EOCD_SIGNATURE = 0x06054b50;
const CENTRAL_DIRECTORY_SIGNATURE = 0x02014b50;
const LOCAL_FILE_SIGNATURE = 0x04034b50;
const MAX_ZIP_COMMENT_LENGTH = 0xffff;
const MAX_DOCX_PARAGRAPHS = 240;
const MAX_PPTX_SLIDES = 80;
const MAX_PPTX_LINES_PER_SLIDE = 80;
const MAX_XLSX_SHEETS = 8;
const MAX_XLSX_ROWS = 80;
const MAX_XLSX_COLUMNS = 20;
const MAX_PREVIEW_CHARS = 120_000;

const OFFICE_KIND_LABELS: Record<WorkspaceOfficePreviewKind, string> = {
  docx: "Word document",
  pptx: "PowerPoint presentation",
  xlsx: "Excel workbook",
};

interface ZipEntry {
  name: string;
  compressedSize: number;
  localHeaderOffset: number;
  method: number;
}

type ZipEntryMap = Map<string, ZipEntry>;

export function isOfficePreviewKind(
  kind: WorkspacePreviewKind
): kind is WorkspaceOfficePreviewKind {
  return kind === "docx" || kind === "xlsx" || kind === "pptx";
}

export function buildOfficePreview(
  filePath: string,
  data: Buffer
): WorkspaceOfficePreview {
  const kind = officePreviewKindForPath(filePath);
  try {
    const entries = listZipEntries(data);
    if (kind === "docx") {
      return buildDocxPreview(kind, entries, data);
    }
    if (kind === "xlsx") {
      return buildXlsxPreview(kind, entries, data);
    }
    return buildPptxPreview(kind, entries, data);
  } catch (error) {
    return {
      kind,
      blocks: [],
      error:
        error instanceof Error ? error.message : "无法解析 Office 文件预览。",
    };
  }
}

export function officePreviewToMarkdown({
  name,
  sourceWorkspacePath,
  preview,
}: {
  name: string;
  sourceWorkspacePath: string;
  preview: WorkspaceOfficePreview;
}): string {
  const sourceRuntimePath = sourceWorkspacePath.replace(/^\/+/, "") || ".";
  const lines = [
    `# ${name}`,
    "",
    "This file was generated by InternAgents during Office attachment upload.",
    "",
    `Source file logical path (file tools): ${sourceWorkspacePath}`,
    `Source file shell/script path: ${sourceRuntimePath}`,
    `Type: ${OFFICE_KIND_LABELS[preview.kind] || preview.kind}`,
    `Truncated: ${preview.truncated ? "yes" : "no"}`,
  ];

  if (preview.error) {
    lines.push("", "## Extraction Error", "", preview.error);
  }

  lines.push("", "## Readable Preview", "");

  const contentBlocks = preview.blocks.filter(
    (block) => block.lines?.length || block.rows?.length
  );
  if (contentBlocks.length === 0) {
    lines.push(
      "No readable text was found. Use the source file when layout, figures, formulas, or manual inspection is required."
    );
    return `${lines.join("\n")}\n`;
  }

  for (const block of contentBlocks) {
    lines.push(`### ${block.title}`, "");
    if (block.rows) {
      lines.push(...rowsToMarkdownTable(block.rows), "");
    } else {
      lines.push(...(block.lines || []), "");
    }
    if (block.truncated) {
      lines.push("_This section was truncated._", "");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function officePreviewKindForPath(
  filePath: string
): WorkspaceOfficePreviewKind {
  const extension = path.extname(filePath).toLowerCase();
  if (extension === ".doc" || extension === ".docx") return "docx";
  if (extension === ".xls" || extension === ".xlsx") return "xlsx";
  if (extension === ".ppt" || extension === ".pptx") return "pptx";
  throw new Error("Unsupported Office file type.");
}

function buildDocxPreview(
  kind: WorkspaceOfficePreviewKind,
  entries: ZipEntryMap,
  data: Buffer
): WorkspaceOfficePreview {
  const documentXml = readZipText(entries, data, "word/document.xml");
  if (!documentXml) {
    throw new Error("未找到 Word 文档正文。");
  }

  const lines: string[] = [];
  let totalChars = 0;
  let truncated = false;
  const paragraphRegex = /<w:p(?:\s[^>]*)?>([\s\S]*?)<\/w:p>/g;
  let match: RegExpExecArray | null;

  while ((match = paragraphRegex.exec(documentXml))) {
    const paragraphXml = match[1]
      .replace(/<w:tab\b[^>]*\/>/g, "\t")
      .replace(/<w:br\b[^>]*\/>/g, "\n");
    const text = normalizePreviewText(
      extractTextNodes(paragraphXml, ["w:t"]).join("")
    );
    if (!text) {
      continue;
    }
    if (lines.length >= MAX_DOCX_PARAGRAPHS) {
      truncated = true;
      break;
    }
    if (totalChars + text.length > MAX_PREVIEW_CHARS) {
      truncated = true;
      break;
    }
    totalChars += text.length;
    lines.push(text);
  }

  return {
    kind,
    blocks: [
      {
        title: "正文",
        lines,
        truncated,
      },
    ],
    truncated,
  };
}

function buildPptxPreview(
  kind: WorkspaceOfficePreviewKind,
  entries: ZipEntryMap,
  data: Buffer
): WorkspaceOfficePreview {
  const slideNames = Array.from(entries.keys())
    .filter((entryName) => /^ppt\/slides\/slide\d+\.xml$/i.test(entryName))
    .sort((left, right) => slideIndex(left) - slideIndex(right));

  if (slideNames.length === 0) {
    throw new Error("未找到演示文稿页面。");
  }

  const blocks: WorkspaceOfficePreviewBlock[] = [];
  let totalChars = 0;
  let truncated = false;

  for (const slideName of slideNames) {
    if (blocks.length >= MAX_PPTX_SLIDES) {
      truncated = true;
      break;
    }
    const xml = readZipText(entries, data, slideName);
    if (!xml) continue;
    const lines = extractTextNodes(xml, ["a:t"])
      .map(normalizePreviewText)
      .filter(Boolean)
      .slice(0, MAX_PPTX_LINES_PER_SLIDE);
    const lineChars = lines.reduce((sum, line) => sum + line.length, 0);
    if (totalChars + lineChars > MAX_PREVIEW_CHARS) {
      truncated = true;
      break;
    }
    totalChars += lineChars;
    blocks.push({
      title: `第 ${slideIndex(slideName)} 页`,
      lines,
      truncated: lines.length >= MAX_PPTX_LINES_PER_SLIDE,
    });
  }

  return {
    kind,
    blocks,
    truncated: truncated || slideNames.length > blocks.length,
  };
}

function buildXlsxPreview(
  kind: WorkspaceOfficePreviewKind,
  entries: ZipEntryMap,
  data: Buffer
): WorkspaceOfficePreview {
  const sharedStrings = parseSharedStrings(
    readZipText(entries, data, "xl/sharedStrings.xml") || ""
  );
  const sheets = getWorkbookSheets(entries, data);
  if (sheets.length === 0) {
    throw new Error("未找到电子表格工作表。");
  }

  const blocks: WorkspaceOfficePreviewBlock[] = [];
  let totalChars = 0;
  let truncated = false;

  for (const sheet of sheets.slice(0, MAX_XLSX_SHEETS)) {
    const xml = readZipText(entries, data, sheet.path);
    if (!xml) continue;
    const rows = parseWorksheetRows(xml, sharedStrings);
    const rowChars = rows.flat().reduce((sum, value) => sum + value.length, 0);
    if (totalChars + rowChars > MAX_PREVIEW_CHARS) {
      truncated = true;
      break;
    }
    totalChars += rowChars;
    blocks.push({
      title: sheet.name,
      rows,
      truncated: rows.length >= MAX_XLSX_ROWS,
    });
  }

  return {
    kind,
    blocks,
    truncated: truncated || sheets.length > blocks.length,
  };
}

function listZipEntries(data: Buffer): ZipEntryMap {
  const eocdOffset = findEndOfCentralDirectory(data);
  if (eocdOffset < 0) {
    throw new Error("无法识别 Office 文件包。");
  }

  const centralDirectorySize = readUInt32(data, eocdOffset + 12);
  const centralDirectoryOffset = readUInt32(data, eocdOffset + 16);
  if (
    centralDirectoryOffset + centralDirectorySize > data.length ||
    centralDirectoryOffset < 0
  ) {
    throw new Error("Office 文件包目录不完整。");
  }

  const entries: ZipEntryMap = new Map();
  let offset = centralDirectoryOffset;
  const end = centralDirectoryOffset + centralDirectorySize;

  while (offset < end) {
    if (readUInt32(data, offset) !== CENTRAL_DIRECTORY_SIGNATURE) {
      throw new Error("Office 文件包目录损坏。");
    }

    const method = readUInt16(data, offset + 10);
    const compressedSize = readUInt32(data, offset + 20);
    const nameLength = readUInt16(data, offset + 28);
    const extraLength = readUInt16(data, offset + 30);
    const commentLength = readUInt16(data, offset + 32);
    const localHeaderOffset = readUInt32(data, offset + 42);
    const nameStart = offset + 46;
    const nameEnd = nameStart + nameLength;
    const name = data
      .subarray(nameStart, nameEnd)
      .toString("utf8")
      .replace(/\\/g, "/");

    if (compressedSize === 0xffffffff || localHeaderOffset === 0xffffffff) {
      throw new Error("暂不支持 ZIP64 Office 文件预览。");
    }

    entries.set(name, {
      name,
      compressedSize,
      localHeaderOffset,
      method,
    });

    offset = nameEnd + extraLength + commentLength;
  }

  return entries;
}

function findEndOfCentralDirectory(data: Buffer): number {
  const minOffset = Math.max(0, data.length - (MAX_ZIP_COMMENT_LENGTH + 22));
  for (let offset = data.length - 22; offset >= minOffset; offset -= 1) {
    if (readUInt32(data, offset) === EOCD_SIGNATURE) {
      return offset;
    }
  }
  return -1;
}

function readZipText(
  entries: ZipEntryMap,
  data: Buffer,
  entryName: string
): string | null {
  const entry = entries.get(entryName);
  if (!entry) {
    return null;
  }
  return readZipEntry(entries, data, entry.name).toString("utf8");
}

function readZipEntry(
  entries: ZipEntryMap,
  data: Buffer,
  entryName: string
): Buffer {
  const entry = entries.get(entryName);
  if (!entry) {
    throw new Error(`Office 文件包缺少 ${entryName}。`);
  }

  const headerOffset = entry.localHeaderOffset;
  if (readUInt32(data, headerOffset) !== LOCAL_FILE_SIGNATURE) {
    throw new Error("Office 文件包内容损坏。");
  }
  const nameLength = readUInt16(data, headerOffset + 26);
  const extraLength = readUInt16(data, headerOffset + 28);
  const dataStart = headerOffset + 30 + nameLength + extraLength;
  const dataEnd = dataStart + entry.compressedSize;
  if (dataEnd > data.length) {
    throw new Error("Office 文件包内容不完整。");
  }

  const compressed = data.subarray(dataStart, dataEnd);
  if (entry.method === 0) {
    return Buffer.from(compressed);
  }
  if (entry.method === 8) {
    return inflateRawSync(compressed);
  }
  throw new Error("暂不支持该 Office 文件压缩方式。");
}

function getWorkbookSheets(
  entries: ZipEntryMap,
  data: Buffer
): Array<{ name: string; path: string }> {
  const workbookXml = readZipText(entries, data, "xl/workbook.xml");
  const relsXml = readZipText(entries, data, "xl/_rels/workbook.xml.rels");
  const relTargets = new Map<string, string>();

  if (relsXml) {
    const relationshipRegex = /<Relationship\b([^>]*)\/?>/g;
    let relMatch: RegExpExecArray | null;
    while ((relMatch = relationshipRegex.exec(relsXml))) {
      const id = getXmlAttribute(relMatch[1], "Id");
      const target = getXmlAttribute(relMatch[1], "Target");
      if (id && target) {
        relTargets.set(id, normalizeWorkbookTarget(target));
      }
    }
  }

  if (workbookXml) {
    const sheets: Array<{ name: string; path: string; index: number }> = [];
    const sheetRegex = /<sheet\b([^>]*)\/?>/g;
    let sheetMatch: RegExpExecArray | null;
    let fallbackIndex = 1;
    while ((sheetMatch = sheetRegex.exec(workbookXml))) {
      const attrs = sheetMatch[1];
      const relationshipId = getXmlAttribute(attrs, "r:id");
      const name = getXmlAttribute(attrs, "name") || `工作表 ${fallbackIndex}`;
      const sheetId =
        Number(getXmlAttribute(attrs, "sheetId")) || fallbackIndex;
      const target = relationshipId
        ? relTargets.get(relationshipId)
        : undefined;
      sheets.push({
        name,
        path: target || `xl/worksheets/sheet${fallbackIndex}.xml`,
        index: sheetId,
      });
      fallbackIndex += 1;
    }
    if (sheets.length > 0) {
      return sheets
        .sort((left, right) => left.index - right.index)
        .map(({ name, path: sheetPath }) => ({ name, path: sheetPath }));
    }
  }

  return Array.from(entries.keys())
    .filter((entryName) => /^xl\/worksheets\/sheet\d+\.xml$/i.test(entryName))
    .sort((left, right) => sheetIndex(left) - sheetIndex(right))
    .map((entryName) => ({
      name: `工作表 ${sheetIndex(entryName)}`,
      path: entryName,
    }));
}

function parseSharedStrings(xml: string): string[] {
  if (!xml) {
    return [];
  }

  const strings: string[] = [];
  const itemRegex = /<si(?:\s[^>]*)?>([\s\S]*?)<\/si>/g;
  let match: RegExpExecArray | null;
  while ((match = itemRegex.exec(xml))) {
    strings.push(
      normalizePreviewText(extractTextNodes(match[1], ["t"]).join(""))
    );
  }
  return strings;
}

function parseWorksheetRows(xml: string, sharedStrings: string[]): string[][] {
  const rows: string[][] = [];
  const rowRegex = /<row\b[^>]*>([\s\S]*?)<\/row>/g;
  let rowMatch: RegExpExecArray | null;

  while ((rowMatch = rowRegex.exec(xml))) {
    if (rows.length >= MAX_XLSX_ROWS) {
      break;
    }
    const row: string[] = [];
    let sequentialColumn = 0;
    const cellRegex = /<c\b([^>]*)>([\s\S]*?)<\/c>/g;
    let cellMatch: RegExpExecArray | null;

    while ((cellMatch = cellRegex.exec(rowMatch[1]))) {
      const attrs = cellMatch[1];
      const cellXml = cellMatch[2];
      const ref = getXmlAttribute(attrs, "r");
      const columnIndex = ref
        ? columnIndexFromCellRef(ref)
        : sequentialColumn++;
      if (columnIndex >= MAX_XLSX_COLUMNS) {
        continue;
      }
      row[columnIndex] = getCellValue(attrs, cellXml, sharedStrings);
    }

    trimTrailingEmptyCells(row);
    if (row.some((value) => Boolean(value))) {
      rows.push(fillSparseRow(row));
    }
  }

  return rows;
}

function getCellValue(
  attrs: string,
  cellXml: string,
  sharedStrings: string[]
): string {
  const type = getXmlAttribute(attrs, "t");
  if (type === "s") {
    const index = Number(extractFirstTagValue(cellXml, "v"));
    return Number.isInteger(index) ? sharedStrings[index] || "" : "";
  }
  if (type === "inlineStr") {
    return normalizePreviewText(extractTextNodes(cellXml, ["t"]).join(""));
  }
  if (type === "b") {
    return extractFirstTagValue(cellXml, "v") === "1" ? "TRUE" : "FALSE";
  }

  const value = extractFirstTagValue(cellXml, "v");
  if (value) {
    return normalizePreviewText(value);
  }
  const formula = extractFirstTagValue(cellXml, "f");
  return formula ? `=${normalizePreviewText(formula)}` : "";
}

function extractTextNodes(xml: string, tags: string[]): string[] {
  const pattern = tags.map(escapeRegExp).join("|");
  const regex = new RegExp(
    `<(${pattern})(?:\\s[^>]*)?>([\\s\\S]*?)<\\/\\1>`,
    "g"
  );
  const values: string[] = [];
  let match: RegExpExecArray | null;
  while ((match = regex.exec(xml))) {
    values.push(decodeXmlEntities(stripXmlTags(match[2])));
  }
  return values;
}

function extractFirstTagValue(xml: string, tag: string): string {
  const safeTag = escapeRegExp(tag);
  const match = new RegExp(
    `<${safeTag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${safeTag}>`
  ).exec(xml);
  return match ? decodeXmlEntities(stripXmlTags(match[1])) : "";
}

function getXmlAttribute(xml: string, name: string): string | undefined {
  const safeName = escapeRegExp(name);
  const match = new RegExp(`(?:^|\\s)${safeName}=(?:"([^"]*)"|'([^']*)')`).exec(
    xml
  );
  const value = match?.[1] ?? match?.[2];
  return value === undefined ? undefined : decodeXmlEntities(value);
}

function normalizeWorkbookTarget(target: string): string {
  const cleanTarget = target.replace(/^\/+/, "");
  const withRoot = cleanTarget.startsWith("xl/")
    ? cleanTarget
    : `xl/${cleanTarget}`;
  return path.posix.normalize(withRoot).replace(/^\.\//, "");
}

function normalizePreviewText(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function stripXmlTags(value: string): string {
  return value.replace(/<[^>]*>/g, "");
}

function decodeXmlEntities(value: string): string {
  return value
    .replace(/&#x([0-9a-f]+);/gi, (_, hex: string) =>
      String.fromCodePoint(Number.parseInt(hex, 16))
    )
    .replace(/&#(\d+);/g, (_, decimal: string) =>
      String.fromCodePoint(Number.parseInt(decimal, 10))
    )
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

function trimTrailingEmptyCells(row: string[]) {
  while (row.length > 0 && !row[row.length - 1]) {
    row.pop();
  }
}

function fillSparseRow(row: string[]): string[] {
  return Array.from({ length: row.length }, (_, index) => row[index] || "");
}

function rowsToMarkdownTable(rows: string[][]): string[] {
  const maxColumns = Math.max(...rows.map((row) => row.length), 0);
  if (rows.length === 0 || maxColumns === 0) {
    return ["No previewable table content."];
  }

  const headers = Array.from({ length: maxColumns }, (_, index) =>
    columnName(index)
  );
  return [
    `| # | ${headers.join(" | ")} |`,
    `| --- | ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row, rowIndex) => {
      const cells = headers.map((_, columnIndex) =>
        escapeMarkdownTableCell(row[columnIndex] || "")
      );
      return `| ${rowIndex + 1} | ${cells.join(" | ")} |`;
    }),
  ];
}

function columnName(index: number): string {
  let value = "";
  let current = index;
  do {
    value = String.fromCharCode(65 + (current % 26)) + value;
    current = Math.floor(current / 26) - 1;
  } while (current >= 0);
  return value;
}

function escapeMarkdownTableCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, "<br>");
}

function columnIndexFromCellRef(ref: string): number {
  const match = /^([A-Z]+)/i.exec(ref);
  if (!match) {
    return 0;
  }
  let index = 0;
  for (const char of match[1].toUpperCase()) {
    index = index * 26 + (char.charCodeAt(0) - 64);
  }
  return Math.max(index - 1, 0);
}

function slideIndex(entryName: string): number {
  return Number(/slide(\d+)\.xml$/i.exec(entryName)?.[1] || "0");
}

function sheetIndex(entryName: string): number {
  return Number(/sheet(\d+)\.xml$/i.exec(entryName)?.[1] || "0");
}

function readUInt16(data: Buffer, offset: number): number {
  if (offset + 2 > data.length) {
    throw new Error("Office 文件包读取越界。");
  }
  return data.readUInt16LE(offset);
}

function readUInt32(data: Buffer, offset: number): number {
  if (offset + 4 > data.length) {
    throw new Error("Office 文件包读取越界。");
  }
  return data.readUInt32LE(offset);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
